services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yaml:/etc/prometheus/rules.yaml"
    networks:
      - localprom
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100

  alert-manager:
    image: prom/alertmanager
    networks:
      - localprom
    ports:
      - 9093:9093
    volumes:
      - ${PWD}/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
      - ${PWD}/password.txt:/etc/alertmanager/password.txt

  test:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: prometheus-test-app
    ports:
      - 5005:5005
    networks:
      - localprom

networks:
  localprom:
    driver: bridge
