version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  run-server:
    cmds:
      - go run ./cmd/server
  rerun:
    cmds:
      - cmd: task stop
        ignore_error: true
      - cmd: docker rmi prometheus-test-app
        ignore_error: true
      - docker compose up -d
  run:
    cmds:
      - cmd: task stop
        ignore_error: true
      - docker compose up -d
  stop:
    cmds:
      - docker compose down
